/**
 * @file CivitasView.java
 * @author Yeray Lopez Ramirez
 * @author Jaime Castillo Ucles
 * @date Diciembre de 2021
 */
package GUI;

import civitas.CivitasJuego;
import civitas.Diario;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import controladorCivitas.Respuesta;
import javax.swing.JOptionPane;

/**
 *
 * @author yerasito
 */
public class CivitasView extends javax.swing.JFrame implements Vista{
    private CivitasJuego juego;
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void setCivitasJuego(CivitasJuego juego){
        this.juego = juego;
        //Escondemos el ranking antes de mostrar el juego
        ranking.setVisible(false);
        rankingLabel.setVisible(false);
        jScrollPane1.setVisible(false);
        
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jugadorPanel1 = new GUI.JugadorPanel();
        jLabel1 = new javax.swing.JLabel();
        casillaActual = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        siguienteOperacion = new javax.swing.JTextField();
        rankingLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ranking = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setText("Civitas");

        jLabel1.setText("CasillaActual:");

        casillaActual.setEditable(false);
        casillaActual.setBorder(null);
        casillaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casillaActualActionPerformed(evt);
            }
        });

        jLabel2.setText("Siguiente Operacion:");

        siguienteOperacion.setEditable(false);
        siguienteOperacion.setBorder(null);
        siguienteOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteOperacionActionPerformed(evt);
            }
        });

        rankingLabel.setText("Ranking");

        ranking.setEditable(false);
        ranking.setColumns(20);
        ranking.setRows(5);
        ranking.setBorder(null);
        jScrollPane1.setViewportView(ranking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rankingLabel)
                        .addGap(556, 556, 556))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(jugadorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(casillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 193, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(543, 543, 543)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(343, 343, 343))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(casillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(siguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(rankingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(jugadorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casillaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casillaActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casillaActualActionPerformed

    private void siguienteOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siguienteOperacionActionPerformed

    @Override
    public void actualiza(){
        jugadorPanel1.setJugador(juego.getJugadorActual());
        int posCasilla = juego.getJugadorActual().getCasillaActual();
        casillaActual.setText(juego.getTablero().getCasilla(posCasilla).toString());
        
        if(juego.finalDelJuego()){
            rankingLabel.setVisible(true);
            ranking.setVisible(true);
            ranking.setText(juego.Ranking().toString());
        }
    }

    @Override
    public void pausa(){
        int val= JOptionPane.showConfirmDialog(null, "¿Continuar?", 
                "Siguiente paso", JOptionPane.YES_NO_OPTION);
        if (val==1) System.exit(0);    
    }
    
    @Override
    public Respuesta comprar(){
        Respuesta respuesta = Respuesta.NO;
        int opcion= 1-JOptionPane.showConfirmDialog(null, "¿Quieres comprar la " +
        "calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
        if(opcion == 1)
            respuesta = Respuesta.SI;
        
        return respuesta;
    }
    
    @Override
    public OperacionInmobiliaria elegirOperacion(){
        GestionarDialog gestion = new GestionarDialog(this);
        
        int opcion = gestion.getGestionElegida(); 
        return OperacionInmobiliaria.eleccion(opcion);
    }
    
    @Override
    public int elegirPropiedad(){
        PropiedadDialog elegirPropiedad = new PropiedadDialog(this,juego.getJugadorActual());
        
        int opcion = elegirPropiedad.getPropiedadElegida(); 
        return opcion;
    }
    
    @Override
    public void mostrarSiguienteOperacion(OperacionJuego operación){
        siguienteOperacion.setText(operación.toString());
        if(operación == OperacionJuego.AVANZAR){
            VistaDado.createInstance(this);
        }
        
        repaint();
    }
    
    @Override
    public void mostrarEventos() {
        DiarioDialog diarioD;
        if (!Diario.getInstance().getEventos().isEmpty())
            diarioD = new DiarioDialog(this); //crea la ventana del diario
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField casillaActual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.JugadorPanel jugadorPanel1;
    private javax.swing.JTextArea ranking;
    private javax.swing.JLabel rankingLabel;
    private javax.swing.JTextField siguienteOperacion;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
