/**
 * @file PropiedadDialog.java
 * @author Yeray Lopez Ramirez
 * @author Jaime Castillo Ucles
 * @date Diciembre de 2021
 */
package GUI;

import civitas.Jugador;
import javax.swing.DefaultListModel;

/**
 *
 * @author yerasito
 */
public class PropiedadDialog extends javax.swing.JDialog {
    int propiedadElegida;
    /**
     * Creates new form PropiedadDialog
     */
    public PropiedadDialog(java.awt.Frame parent, Jugador jugadorActual) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(null);
        propLabel.setText("Gestiones");
        propiedadElegida = -1;
        
        DefaultListModel propiedades = new DefaultListModel<>(); // datos para la lista
        for (int i = 0; i < jugadorActual.getPropiedades().size(); i++)
            propiedades.addElement(jugadorActual.getPropiedades().get(i));
        
             //se completan los datos
        listaPropiedades.setModel(propiedades); //se le dice a la lista cuáles son esos datos
        setVisible(true);
    }
    
    int getPropiedadElegida(){
        return propiedadElegida;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPropiedades = new javax.swing.JList<>();
        realizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        propLabel.setText("Propiedad:");
        getContentPane().add(propLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 38, -1, -1));

        listaPropiedades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaPropiedades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPropiedadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaPropiedades);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 61, 981, 120));

        realizar.setText("REALIZAR");
        getContentPane().add(realizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(774, 236, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaPropiedadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPropiedadesMouseClicked
        propiedadElegida = listaPropiedades.getSelectedIndex();
        dispose();
    }//GEN-LAST:event_listaPropiedadesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaPropiedades;
    private javax.swing.JLabel propLabel;
    private javax.swing.JButton realizar;
    // End of variables declaration//GEN-END:variables
}
