/**
 * @file VistaDado.java
 * @author Yeray Lopez Ramirez
 * @author Jaime Castillo Ucles
 * @date Diciembre de 2021
 */
package GUI;

import civitas.Dado;

/**
 *
 * @author mabad
 */
public class VistaDado extends javax.swing.JDialog {

    /**
     * Creates new form VistaDado
     */
    
    private static Dado dado=Dado.getInstance();
    private static VistaDado instance;
    
    private VistaDado(java.awt.Frame parent) {
        super(parent, true);
       
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public static VistaDado createInstance(java.awt.Frame parent)
    {
        if (instance==null) instance=new VistaDado(parent);
        
        instance.dadoLabel.setText(Integer.toString(dado.getUltimoResultado()));
        update();
        return instance;
    }
    
    private static void update()
    {
    if (dado.getDebug()) 
    {
        instance.debugLabel.setVisible(true);
        instance.debugButton.setText("Cambiar a modo normal");
    }
        else 
    {
        instance.debugLabel.setVisible(false);
        instance.debugButton.setText("Cambiar a modo debug");
    }
    
        instance.setVisible(true);
        instance.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dadoLabel = new javax.swing.JLabel();
        dadoButton = new javax.swing.JButton();
        debugLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        debugButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dadoLabel.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        dadoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dadoLabel.setText("jLabel1");
        dadoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        dadoLabel.setMaximumSize(new java.awt.Dimension(83, 83));
        dadoLabel.setMinimumSize(new java.awt.Dimension(83, 83));
        dadoLabel.setPreferredSize(new java.awt.Dimension(83, 83));
        getContentPane().add(dadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 24, -1, -1));

        dadoButton.setText("Continuar");
        dadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dadoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 123, -1, -1));

        debugLabel.setForeground(new java.awt.Color(242, 9, 9));
        debugLabel.setText("Modo debug");
        getContentPane().add(debugLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        tituloLabel.setText("Valor del dado:");
        getContentPane().add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, -1, -1));

        debugButton.setText("cambiar modo");
        debugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugButtonActionPerformed(evt);
            }
        });
        getContentPane().add(debugButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, 219, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadoButtonActionPerformed
        // TODO add your handling code here:
dispose();
    }//GEN-LAST:event_dadoButtonActionPerformed

    private void debugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debugButtonActionPerformed
        // TODO add your handling code here:
if (dado.getDebug()) dado.setDebug(false);
else dado.setDebug(true);
update();
    }//GEN-LAST:event_debugButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dadoButton;
    private javax.swing.JLabel dadoLabel;
    private javax.swing.JButton debugButton;
    private javax.swing.JLabel debugLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
