module Estado_juego
  EN_ENTRADA_LABERINTO=0
  DENTRO_VIVO=1
  EN_SALIDA_LABERINTO=2
  DENTRO_MUERTO=3
end
Lista_estados=Array["EN_ENTRADA_LABERINTO", "DENTRO_VIVO", "EN_SALIDA_LABERINTO", "DENTRO_MUERTO"]